### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by hellozjf** [hexojs/hexo-generator-index#10]
When I run `npm run test-cov`, then I get some errors
```
[zjf@aliyun hexo-generator-index]$ npm run test-cov

> hexo-generator-index@0.2.1 test-cov /home/zjf/git/hexo-generator-index
> istanbul cover --print both _mocha -- test/index.js



(node:3175) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
  Index generator
    1) "before all" hook


  0 passing (26ms)
  1 failing

  1) Index generator "before all" hook:
     TypeError: Cannot read property 'call' of undefined
      at Model._Document.Document.<anonymous> (node_modules/_hexo@3.3.7@hexo/lib/models/post.js:60:30)
      at Model._Document.Document.permalink (node_modules/_warehouse@2.2.0@warehouse/lib/types/virtual.js:70:22)
      at Model._Document.Document.Document.toObject (node_modules/_warehouse@2.2.0@warehouse/lib/document.js:79:42)
      at Database._Model.Model.Model._insertOne (node_modules/_warehouse@2.2.0@warehouse/lib/model.js:189:21)
      at node_modules/_warehouse@2.2.0@warehouse/lib/model.js:214:17
      at tryCatcher (node_modules/_bluebird@3.5.0@bluebird/js/release/util.js:16:23)
      at node_modules/_bluebird@3.5.0@bluebird/js/release/using.js:185:26
      at tryCatcher (node_modules/_bluebird@3.5.0@bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:693:18)
      at Promise._fulfill (node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:638:18)
      at PromiseArray._resolve (node_modules/_bluebird@3.5.0@bluebird/js/release/promise_array.js:126:19)
      at PromiseArray._promiseFulfilled (node_modules/_bluebird@3.5.0@bluebird/js/release/promise_array.js:144:14)
      at Promise._settlePromise (node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/_bluebird@3.5.0@bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/_bluebird@3.5.0@bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/_bluebird@3.5.0@bluebird/js/release/async.js:17:14)



=============================================================================
Writing coverage object [/home/zjf/git/hexo-generator-index/coverage/coverage.json]
Writing coverage reports at [/home/zjf/git/hexo-generator-index/coverage]
=============================================================================
---------------|----------|----------|----------|----------|----------------|
File           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------|----------|----------|----------|----------|----------------|
 lib/          |    28.57 |        0 |        0 |    28.57 |                |
  generator.js |    28.57 |        0 |        0 |    28.57 |     6,7,8,9,11 |
---------------|----------|----------|----------|----------|----------------|
All files      |    28.57 |        0 |        0 |    28.57 |                |
---------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 28.57% ( 2/7 )
Branches     : 0% ( 0/4 )
Functions    : 0% ( 0/1 )
Lines        : 28.57% ( 2/7 )
================================================================================
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-generator-index@0.2.1 test-cov: `istanbul cover --print both _mocha -- test/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexo-generator-index@0.2.1 test-cov script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zjf/.npm/_logs/2017-06-25T17_02_28_120Z-debug.log
```
I don't know how to solve it, can anyone help me?

**Comment by NoahDragon** [comment]
I recently notice such error. I will take a look at it.

**Comment by NoahDragon** [comment]
I have made some changes in #11. Could you please have a try?

**Comment by hellozjf** [comment]
It's OK now. Thank you @NoahDragon
